# sivmone: Fast Sila Virtual Machine implementation
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get -q update && sudo apt-get -qy install build-essential libgmp-dev
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DEVMONE_TESTING=ON -DCMAKE_COMPILE_WARNING_AS_ERROR=TRUE
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure --parallel 4
